# Vectors, Matrices, and Arrays in NumPy

NumPy is a foundational tool of the Python machine learning stack. NumPy allows for efficient operations on the data structures often used in machine learning: vectors, matrices, and tensors. While NumPy isn’t the focus of this book, it will show up frequently in the following chapters. This chapter covers the most common NumPy operations we’re likely to run into while working on machine learning workflows.

## Creating a Vector

In [1]:
# Load library
import numpy as np

In [5]:
# Create a vector as a row
vector_row = np.array([1, 2, 3])

print(vector_row)

[1 2 3]


In [6]:
# Create a vector as a column
vector_column = np.array([[1],
                          [2],
                          [3]])

print(vector_column)

[[1]
 [2]
 [3]]


NumPy’s main data structure is the multidimensional array. A vector is just an array with a single dimension. To create a vector, we simply create a one-dimensional array. Just like vectors, these arrays can be represented horizontally (i.e., rows) or vertically (i.e., columns).

## Creating a Matrix

In [7]:
# Load library
import numpy as np

In [8]:
# Create a matrix
matrix = np.array([[1, 2],
                   [1, 2],
                   [1, 2]])

print(matrix)

[[1 2]
 [1 2]
 [1 2]]


To create a matrix we can use a NumPy two-dimensional array. In our solution, the matrix contains three rows and two columns (a column of 1s and a column of 2s).

NumPy actually has a dedicated matrix data structure:

In [9]:
matrix_object = np.mat([[1, 2],
                        [1, 2],
                        [1, 2]])

print(matrix_object)

[[1 2]
 [1 2]
 [1 2]]


However, the matrix data structure is not recommended for two reasons. First, arrays are the de facto standard data structure of NumPy. Second, the vast majority of NumPy operations return arrays, not matrix objects.

## Creating a Sparse Matrix

In [12]:
# Load library
import numpy as np
from scipy import sparse

In [13]:
# Create a matrix
matrix = np.array([[0, 0],
                   [0, 1],
                   [3, 0]])

print(matrix)

[[0 0]
 [0 1]
 [3 0]]


A frequent situation in machine learning is having a huge amount of data; however, most of the elements in the data are zeros. For example, imagine a matrix where the columns are every movie on Netflix, the rows are every Netflix user, and the values are how many times a user has watched that particular movie. This matrix would have tens of thousands of columns and millions of rows! However, since most users do not watch most movies, the vast majority of elements would be zero.

A sparse matrix is a matrix in which most elements are 0. Sparse matrices store only nonzero elements and assume all other values will be zero, leading to significant computational savings. In our solution, we created a NumPy array with two nonzero values, then converted it into a sparse matrix. If we view the sparse matrix we can see that only the nonzero values are stored:

In [14]:
# Create compressed sparse row (CSR) matrix
matrix_sparse = sparse.csr_matrix(matrix)

print(matrix_sparse)

  (1, 1)	1
  (2, 0)	3


There are a number of types of sparse matrices. However, in compressed sparse row (CSR) matrices, (1, 1) and (2, 0) represent the (zero-indexed) indices of the nonzero values 1 and 3, respectively. For example, the element 1 is in the second row and second column. We can see the advantage of sparse matrices if we create a much larger matrix with many more zero elements and then compare this larger matrix with our original sparse matrix:

In [16]:
# Create larger matrix
matrix_large = np.array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                         [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
                         [3, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

print(matrix_large)

[[0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [3 0 0 0 0 0 0 0 0 0]]


In [19]:
# Create compressed sparse row (CSR) matrix
matrix_large_sparse = sparse.csr_matrix(matrix_large)
# View original sparse matrix
print(matrix_sparse)

print('\n')

# View larger sparse matrix
print(matrix_large_sparse)

  (1, 1)	1
  (2, 0)	3


  (1, 1)	1
  (2, 0)	3


As we can see, despite the fact that we added many more zero elements in the larger matrix, its sparse representation is exactly the same as our original sparse matrix. That is, the addition of zero elements did not change the size of the sparse matrix.

As mentioned, there are many different types of sparse matrices, such as compressed sparse column, list of lists, and dictionary of keys. While an explanation of the different types and their implications is outside the scope of this book, it is worth noting that while there is no “best” sparse matrix type, there are meaningful differences among them, and we should be conscious about why we are choosing one type over another.

## Preallocating NumPy Arrays

In [1]:
# Load library
import numpy as np

In [7]:
# Generate a vector of shape (1,5) containing all zeros
vector = np.zeros(shape=5)

print(vector)

[0. 0. 0. 0. 0.]


In [9]:
# Generate a matrix of shape (3,3) containing all ones
matrix = np.full(shape=(3,3), fill_value=1)

print(matrix)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


Generating arrays prefilled with data is useful for a number of purposes, such as making code more performant or using synthetic data to test algorithms. In many programming languages, preallocating an array of default values (such as 0s) is considered common practice.

## Selecting Elements

In [ ]:
# Load library
import numpy as np

In [13]:
# Create row vector
vector = np.array([1, 2, 3, 4, 5, 6])

# Create matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Select third element of vector
print(vector[2])

print('\n')

# Select second row, second column
print(matrix[1,1])

3


5


Like most things in Python, NumPy arrays are zero-indexed, meaning that the index of the first element is 0, not 1. With that caveat, NumPy offers a wide variety of methods for selecting (i.e., indexing and slicing) elements or groups of elements in arrays:

In [42]:
# Select all elements of a vector
vector[:]

array([1, 2, 3, 4, 5, 6])

In [43]:
# Select everything up to and including the third element
vector[:3]

array([1, 2, 3])

In [44]:
# Select everything after the third element
vector[3:]

array([4, 5, 6])

In [45]:
# Select the last element
vector[-1]

6

In [46]:
# Reverse the vector
vector[::-1]

array([6, 5, 4, 3, 2, 1])

In [47]:
# Select the first two rows and all columns of a matrix
matrix[:2,:]

array([[1, 2, 3],
       [4, 5, 6]])

In [48]:
# Select all rows and the second column
matrix[:,1:2]

array([[ 2],
       [ 5],
       [ 8],
       [11]])

## Describing a Matrix

In [14]:
# Load library
import numpy as np

In [15]:
# Create matrix
matrix = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]])

In [16]:
# View number of rows and columns
matrix.shape

(3, 4)

In [17]:
# View number of elements (rows * columns)
matrix.size

12

In [18]:
# View number of dimensions
matrix.ndim

2

This might seem basic (and it is); however, time and again it will be valuable to check the shape and size of an array both for further calculations and simply as a gut check after an operation.

## Applying Functions over Each Element

In [19]:
# Load library
import numpy as np

In [20]:
# Create matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

In [21]:
# Create function that adds 100 to something
add_100 = lambda i: i + 100

In [22]:
# Create vectorized function
vectorized_add_100 = np.vectorize(add_100)

In [23]:
# Apply function to all elements in matrix
vectorized_add_100(matrix)

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

The NumPy vectorize method converts a function into a function that can apply to all elements in an array or slice of an array. It’s worth noting that vectorize is essentially a for loop over the elements and does not increase performance. Furthermore, NumPy arrays allow us to perform operations between arrays even if their dimensions are not the same (a process called broadcasting). For example, we can create a much simpler version of our solution using broadcasting:

In [49]:
# Add 100 to all elements
matrix + 100

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109],
       [110, 111, 112]])

Broadcasting does not work for all shapes and situations, but it is a common way of applying simple operations over all elements of a NumPy array.

## Finding the Maximum and Minimum Values

In [24]:
# Load library
import numpy as np

In [25]:
# Create matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

In [26]:
# Return maximum element
np.max(matrix)

9

In [27]:
# Return minimum element
np.min(matrix)

1

Often we want to know the maximum and minimum value in an array or subset of an array. This can be accomplished with the max and min methods. Using the axis parameter, we can also apply the operation along a certain axis:

In [28]:
# Find maximum element in each column
np.max(matrix, axis=0)

array([7, 8, 9])

In [29]:
# Find maximum element in each row
np.max(matrix, axis=1)

array([3, 6, 9])

## Calculating the Average, Variance, and Standard Deviation

In [30]:
# Load library
import numpy as np

In [31]:
# Create matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

In [32]:
# Return mean
np.mean(matrix)

5.0

In [33]:
# Return variance
np.var(matrix)

6.666666666666667

In [34]:
# Return standard deviation
np.std(matrix)

2.581988897471611

Just like with max and min, we can easily get descriptive statistics about the whole matrix or do calculations along a single axis:

In [35]:
# Find the mean value in each column
np.mean(matrix, axis=0)

array([4., 5., 6.])

## Reshaping Arrays

In [36]:
# Load library
import numpy as np


In [37]:
# Create 4x3 matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9],
                   [10, 11, 12]])

In [38]:
# Reshape matrix into 2x6 matrix
matrix.reshape(2, 6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

reshape allows us to restructure an array so that we maintain the same data but organize it as a different number of rows and columns. The only requirement is that the shape of the original and new matrix contain the same number of elements (i.e., are the same size). We can see the size of a matrix using size:

In [39]:
matrix.size

12

One useful argument in reshape is -1, which effectively means “as many as needed,” so reshape(1, -1) means one row and as many columns as needed:

In [40]:
matrix.reshape(1, -1)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

Finally, if we provide one integer, reshape will return a one-dimensional array of that length:

In [41]:
matrix.reshape(12)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

## Transposing a Vector or Matrix

In [50]:
# Load library
import numpy as np

In [51]:
# Create matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

In [52]:
# Transpose matrix
matrix.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

Transposing is a common operation in linear algebra where the column and row indices of each element are swapped. A nuanced point typically overlooked outside of a linear algebra class is that, technically, a vector can’t be transposed because it’s just a collection of values:

In [53]:
# Transpose vector
np.array([1, 2, 3, 4, 5, 6]).T

array([1, 2, 3, 4, 5, 6])

However, it is common to refer to transposing a vector as converting a row vector to a column vector (notice the second pair of brackets) or vice versa:

In [54]:
# Transpose row vector
np.array([[1, 2, 3, 4, 5, 6]]).T

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

## Flattening a Matrix

In [55]:
# Load library
import numpy as np

In [56]:
# Create matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

In [57]:
# Flatten matrix
matrix.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

flatten is a simple method to transform a matrix into a one-dimensional array. Alternatively, we can use reshape to create a row vector:

In [58]:
matrix.reshape(1, -1)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

Another common way to flatten arrays is the ravel method. Unlike flatten, which returns a copy of the original array, ravel operates on the original object itself and is therefore slightly faster. It also lets us flatten lists of arrays, which we can’t do with the flatten method. This operation is useful for flattening very large arrays and speeding up code:

In [59]:
# Create one matrix
matrix_a = np.array([[1, 2],
                     [3, 4]])

# Create a second matrix
matrix_b = np.array([[5, 6],
                     [7, 8]])

In [60]:
# Create a list of matrices
matrix_list = [matrix_a, matrix_b]

In [62]:
# Flatten the entire list of matrices
np.ravel(matrix_list)

array([1, 2, 3, 4, 5, 6, 7, 8])

## Finding the Rank of a Matrix

In [63]:
# Load library
import numpy as np

In [64]:
# Create matrix
matrix = np.array([[1, 1, 1],
                   [1, 1, 10],
                   [1, 1, 15]])

In [65]:
# Return matrix rank
np.linalg.matrix_rank(matrix)

2

The rank of a matrix is the dimensions of the vector space spanned by its columns or rows. Finding the rank of a matrix is easy in NumPy thanks to matrix_rank.

## Getting the Diagonal of a Matrix

In [66]:
# Load library
import numpy as np

In [67]:
# Create matrix
matrix = np.array([[1, 2, 3],
                   [2, 4, 6],
                   [3, 8, 9]])

In [68]:
# Return diagonal elements
matrix.diagonal()

array([1, 4, 9])

NumPy makes getting the diagonal elements of a matrix easy with diagonal. It is also possible to get a diagonal off the main diagonal by using the offset parameter:

In [69]:
# Return diagonal one above the main diagonal
matrix.diagonal(offset=1)

array([2, 6])

In [70]:
# Return diagonal one below the main diagonal
matrix.diagonal(offset=-1)

array([2, 8])

## Calculating the Trace of a Matrix

In [ ]:
# Load library
import numpy as np

In [71]:
# Create matrix
matrix = np.array([[1, 2, 3],
                   [2, 4, 6],
                   [3, 8, 9]])

In [72]:
# Return trace
matrix.trace()

14

The trace of a matrix is the sum of the diagonal elements and is often used under the hood in machine learning methods. Given a NumPy multidimensional array, we can calculate the trace using trace. Alternatively, we can return the diagonal of a matrix and calculate its sum:

In [73]:
# Return diagonal and sum elements
sum(matrix.diagonal())

14

## Calcualting the Dot Products

In [74]:
# Load library
import numpy as np

In [75]:
# Create two vectors
vector_a = np.array([1,2,3])

In [76]:
vector_b = np.array([4,5,6])

In [77]:
# Calculate dot product
np.dot(vector_a, vector_b)

32

The dot product of two vectors,  and , is defined as:
n
E aibi
i=1 

where 
 is the th element of vector , and 
 is the th element of vector . We can use NumPy’s dot function to calculate the dot product. Alternatively, in Python 3.5+ we can use the new @ operator:

In [78]:
# Calculate dot product
vector_a @ vector_b

32

## Adding and Subtracting Matrices

In [79]:
# Load library
import numpy as np

In [80]:

# Create matrix
matrix_a = np.array([[1, 1, 1],
                     [1, 1, 1],
                     [1, 1, 2]])

In [81]:
# Create matrix
matrix_b = np.array([[1, 3, 1],
                     [1, 3, 1],
                     [1, 3, 8]])

In [82]:
# Add two matrices
np.add(matrix_a, matrix_b)

array([[ 2,  4,  2],
       [ 2,  4,  2],
       [ 2,  4, 10]])

In [83]:
# Subtract two matrices
np.subtract(matrix_a, matrix_b)

array([[ 0, -2,  0],
       [ 0, -2,  0],
       [ 0, -2, -6]])

Alternatively, we can simply use the + and – operators:

In [84]:
# Add two matrices
matrix_a + matrix_b

array([[ 2,  4,  2],
       [ 2,  4,  2],
       [ 2,  4, 10]])

## Multiplying Matrices

In [85]:
# Load library
import numpy as np

In [86]:
# Create matrix
matrix_a = np.array([[1, 1],
                     [1, 2]])

In [87]:
# Create matrix
matrix_b = np.array([[1, 3],
                     [1, 2]])

In [88]:
# Multiply two matrices
np.dot(matrix_a, matrix_b)

array([[2, 5],
       [3, 7]])

Alternatively, in Python 3.5+ we can use the @ operator:

In [89]:
# Multiply two matrices
matrix_a @ matrix_b

array([[2, 5],
       [3, 7]])

If we want to do element-wise multiplication, we can use the * operator:

In [90]:
# Multiply two matrices element-wise
matrix_a * matrix_b

array([[1, 3],
       [1, 4]])

## Inverting a Matrix

In [91]:
# Load library
import numpy as np

In [92]:
# Create matrix
matrix = np.array([[1, 4],
                   [2, 5]])

In [93]:
# Calculate inverse of matrix
np.linalg.inv(matrix)

array([[-1.66666667,  1.33333333],
       [ 0.66666667, -0.33333333]])